---
title: "Problem solving task 1, MXB262 2021"
author: "Dr Kate Helmstedt"
date: "Due Sunday 23 March at 11:59pm"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


**If this PS submission is not written in an R markdown that we are able to knit, you will receive maximum 50% of the total grade for PST 1. **For this reason, please make an R markdown file as soon as possible that contains all of your images. This is critical to your success in this and all PS tasks in MXB262, so get on top of it during your workshop or over Slack.

**Submit** the R markdown file, the knitted html or pdf file, and all image files through Blackboard. It is easiest to put all files into a folder and zip it up, submitting the .zip file. 

Total marks are out of 20, worth 6% of your total grade for this unit.

### Questions

1. (**Marks: 8/20,** but if you haven't embedded the image so that we can see them in the knitted file, you will receive maximum 50%.)  Use the principles of stort-telling practiced in the workshop to create a story board. Don't forget to report where you got the visualisation from (including the URL) so we can click through and see its environment. Please choose from these categories:
    * one figure from a paper that one of your lecturers (not Kate!), or any academic you know from QUT or elsewhere has published. Most academics will have a [Google Scholar](scholar.google.com) website, so search them up and browse their papers
    * either [fivethirtyeight](fivethiryeight.com), [The Guardian](theguardian.com), or another online news source
    * either [#tidytuesday on Twitter](https://twitter.com/search?q=%23tidytuesday&src=typed_query), [r/dataisbeautiful on Reddit](https://www.reddit.com/r/dataisbeautiful/)

2. (**Marks: 10/20**) Choose one of the papers in the readings for this week. In your own words (i.e. without using direct quotes from the paper), and using only information from the paper, answer the following questions: (maximum 300 words)
    (a) What is the main argument of the paper?
    (b) According to this paper, why is effective visual communication important (or not)?
    (c) What are the key elements, considerations, or factors to be considered for effective visual communication addressed in the paper? Do you disagree with any?
    (d) What pitfalls are identified in the paper that can be avoided if we use effective visual communication?


3. (**Marks: 2/20**) Direct message Kate on Slack with one sentence: what have you found most challenging about the programming in this unit so far?




